#! /bin/sh
### BEGIN INIT INFO
# Provides:          dionaea
# Required-Start:    $network
# Required-Stop:     $network
# Should-Start:
# Should-Stop:
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
### END INIT INFO

PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
DAEMON=/opt/dionaea/bin/dionaea
NAME=dionaea
GROUP=dionaea
CONFIG_FILE="/opt/dionaea/etc/dionaea/dionaea.conf"
#dionaea -u nobody -g nogroup -r /opt/dionaea/ -w /opt/dionaea -p /opt/dionaea/var/dionaea.pid
DAEMON_OPTS="-u $NAME -g $GROUP -l all,-debug -L '*'  -w /opt/dionaea -c $CONFIG_FILE"

test -x $DAEMON || exit 0

set -e

case "$1" in
  start)
	echo -n "Starting $NAME: "
	start-stop-daemon --start --quiet --oknodo --pidfile /opt/dionaea/var/$NAME.pid \
	--background --make-pidfile --exec $DAEMON -- $DAEMON_OPTS
	echo "$NAME."
	;;
  stop)
	echo -n "Stopping $NAME: "
	start-stop-daemon --stop --quiet --oknodo --pidfile /opt/dionaea/var/$NAME.pid \
	--signal 15 --exec $DAEMON
	echo "$NAME."
	;;
  restart|force-reload)
	echo -n "Restarting $NAME: "
	start-stop-daemon --stop --quiet --oknodo --pidfile /opt/dionaea/var/$NAME.pid \
	--signal 15 --exec $DAEMON
	sleep 1
	start-stop-daemon --start --quiet --oknodo --pidfile /opt/dionaea/var/$NAME.pid \
	--background --make-pidfile --exec $DAEMON -- $DAEMON_OPTS
	echo "$NAME."
	;;
  status)
    	if [ -e $PIDFILE ]; then
        	status_of_proc -p $PIDFILE $DAEMON "$NAME process" && exit 0 || exit $?
    	else
        	echo "$DAEMON is not running ..."
    	fi
	;;
  *)
	N=/etc/init.d/$NAME
	echo "Usage: $N {start|stop|restart|force-reload|status}" >@2
	exit 1
	;;
esac

exit 0
