#!/bin/bash
### BEGIN INIT INFO
# Provides:          dionaeafr
# Required-Start:    $network
# Required-Stop:     $network
# Should-Start:
# Should-Stop:
# Description:       Run dionaeafr, access portal via http://0.0.0.0:8000
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
### END INIT INFO

# https://github.com/phage-nz/malware-hunting/blob/master/honeypot/dionaeafr.init

. /lib/lsb/init-functions

BASEDIR="/opt/DionaeaFR"
PIDFOLDER="/var/run/dionaeafr"
PIDFILE=$PIDFOLDER/dionaeafr.pid
LOGFILE="/var/log/dionaeafr/dionaeafr.log"
NAME="dionaeafr"
DAEMON="dionaeafr"
PORT=8000

if [ ! -d "$PIDFOLDER" ]; then
  mkdir $PIDFOLDER
fi

case $1 in
  start)
    cd $BASEDIR
    python manage.py runserver 0.0.0.0:$PORT > $LOGFILE 2>> $LOGFILE &
    echo "$DAEMON started ..."
  ;;
  stop)
    if [ -e $PIDFILE ]; then
        kill `cat $PIDFILE`
        rm $PIDFILE
        echo "$DAEMON stopped ..."
    else
        echo "$DAEMON is *NOT* running"
    fi
  ;;
  collectstatic)
    cd $BASEDIR
    python manage.py collectstatic
  ;;
  logs)
    cat $LOGFILE
  ;;
  status)
    if [ -e $PIDFILE ]; then
        status_of_proc -p $PIDFILE $DAEMON "$NAME process" && exit 0 || exit $?
    else
        echo "$DAEMON is not running ..."
    fi
  ;;
  *)
  # For invalid arguments, print the usage message.
  echo "Usage: $0 {start|stop|collectstatic|logs|status}"
  exit 2
  ;;    
esac
