#!/bin/bash
### BEGIN INIT INFO
# Provides: dionaea
# Required-Start: $network $syslog
# Required-Stop:  $network $syslog
# Default-Start:  2 3 4 5
# Default-Stop:
# Short-Description:	Dionaea honeypot
### END INIT INFO

#If restarting the honeypot  and dionaea has not started the following command ran run dionaea in the background.
#sudo /opt/dionaea/bin/dionaea > /dev/null &

# after placing file into init.d, must run:
#    sudo update-rc.d dionaea defaults


. /lib/lsb/init-functions

BASEDIR="/opt/dionaea"
PIDFOLDER="/opt/dionaea/var"
PIDFILE=$PIDFOLDER/dionaea.pid
LOGFILE="/opt/dionaea/var/log/dionaea.log"
CONFIG="/opt/dionaea/etc/dionaea/dionaea.cfg"
NAME="dionaea"
DAEMON="dionaea"
USER="nobody"
GROUP="nogroup"

if [ ! -d "$PIDFOLDER" ]; then
  mkdir $PIDFOLDER
fi

case $1 in
  start)
    cd $BASEDIR
    /opt/dionaea/bin/dionaea -u $USER -g $GROUP -c $CONFIG -w $BASEDIR -p $PIDFILE -D > $LOGFILE 2>> $LOGFILE &
    log_daemon_msg "$DAEMON started ..."
    log_end_msg 0
  ;;
  stop)
    if [ -e $PIDFILE ]; then
        kill `cat $PIDFILE`
        rm $PIDFILE
        log_daemon_msg "$DAEMON stopped ..."
        log_end_msg 0
    else
        log_daemon_msg "$DAEMON is *NOT* running"
        log_end_msg 1
    fi
  ;;
  logs)
    cat $LOGFILE
  ;;
  status)
    if [ -e $PIDFILE ]; then
        status_of_proc -p $PIDFILE $DAEMON "$NAME process" && exit 0 || exit $?
    else
        log_daemon_msg "$DAEMON is not running ..."
        log_end_msg 0
    fi
  ;;
  *)
  # For invalid arguments, print the usage message.
  echo "Usage: $0 {start|stop|logs|status}"
  exit 2
  ;;    
esac
