#!/bin/bash
### BEGIN INIT INFO
# Provides: GCRdionaeaAlerts
# Required-Start: $network  
# Required-Stop:  $network  
# Default-Start:  2 3 4 5 
# Default-Stop:
# Short-Description:	GCR enhanced dionaea syslogs utility
### END INIT INFO


# after placing file into init.d, must run:
#    sudo update-rc.d gcr-enhanced-log defaults

. /lib/lsb/init-functions

BASEDIR="/opt/dionaea"
PIDFOLDER="/opt/dionaea/var/"
PIDFILE=$PIDFOLDER/gcr-enhanced-log.pid
LOGFILE="/opt/dionaea/var/log/gcr-enhanced-log.log"
NAME="GCRdionaeaAlerts"
DAEMON="gcr-enhanced-log"
USER="nobody"
GROUP="nobody"

if [ ! -d "$PIDFOLDER" ]; then
  mkdir $PIDFOLDER
fi

case $1 in
  start)
    cd $BASEDIR
    start-stop-daemon --start --oknodo —user nobody --name GCRdionaeaAlerts --pidfile $PIDFILE --startas $BASEDIR/bin/GCRdionaeaAlerts.py -- --daemon
#    python3 /opt/dionaea/bin/GCRdionaeaAlerts.py & > $LOGFILE 2>> $LOGFILE &
    log_daemon_msg "$DAEMON started ..."
    log_end_msg 0
  ;;
  stop)
    if [ -e $PIDFILE ]; then
        kill `cat $PIDFILE`
        rm $PIDFILE
        log_daemon_msg "$DAEMON stopped ..."
        log_end_msg 0
    else
        log_daemon_msg "$DAEMON is *NOT* running"
        log_end_msg 1
    fi
  ;;
  logs)
    cat $LOGFILE
  ;;
  status)
    if [ -e $PIDFILE ]; then
        status_of_proc -p $PIDFILE $DAEMON "$NAME process" && exit 0 || exit $?
    else
        log_daemon_msg "$DAEMON is not running ..."
        log_end_msg 0
    fi
  ;;
  *)
  # For invalid arguments, print the usage message.
  echo "Usage: $0 {start|stop|logs|status}"
  exit 2
  ;;    
esac
