#!/usr/bin/env bash
# Reference: https://avleonov.com/2017/04/10/installing-openvas-9-from-the-sources/

### BEGIN INIT INFO
# Provides:          openvas_start
# Required-Start:    
# Required-Stop:     
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: A basic startup script to start OpenVAS
# Description:       A basic startup script to
#                    open the required components
#                    needed for OpenVAS.
### END INIT INFO

mkdir /usr/local/var/run 2>/dev/null; 
mkdir /usr/local/var/run/openvasmd 2>/dev/null; 
touch /usr/local/var/run/openvasmd/openvasmd.pid;

/usr/local/sbin/openvasmd
/usr/local/sbin/openvassd
/usr/local/sbin/gsad
