# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile
Vagrant.configure(2) do |config|
 config.vm.provider :aws do |aws, override|
   aws.access_key_id = ENV['AWS_KEY']
   aws.secret_access_key = ENV['AWS_SECRET']
   aws.keypair_name = ENV['AWS_KEYNAME']
   aws.ami = "ami-b3cf71d7"
   aws.region = "ca-central-1" 
   aws.instance_type = "t2.micro"
   aws.security_groups = ["sg-ddd616b5"]
   aws.subnet_id = "subnet-3bcbb040"
   aws.elastic_ip = "35.182.144.45"

   override.nfs.functional = false
   override.vm.box = "dummy"
   override.ssh.username = "ubuntu"
   override.ssh.private_key_path = ENV['AWS_KEYPATH']
   config.vm.provider "aws" do |aws|

   aws.tags = {
    'Name' => 'Phase1-Syslog-Server-TESTING',
	  'Organization' => 'GCR',
    'Developer' => 'GCR Script',
	  'Function' => 'Syslog Server TESTING'
    }  
   end
  end

  # get rid of the inline SHELL below and keep the echo, convert rest to an ansible playbook
  # config.vm.provision :shell, path: "bootstrap.sh"

  config.vm.provision "shell", inline: <<-SHELL
     apt-get -qq update
     apt-get -qq install -y python-pip libssl-dev
     echo "127.0.0.1 $(hostname)" >> /etc/hosts
     export DEBIAN_FRONTEND=noninteractive
     apt-get -qq install -y python-minimal
     pip -q install --upgrade pip
     rm /usr/bin/python
     ln -s /usr/bin/python2.7 /usr/bin/python
     pip install ansible
     # install canary software
     apt-get -qq install -y unzip
     # add in syslog setup
     # Reference: https://www.howtoforge.com/centralized-rsyslog-server-monitoring
     apt-get -qq -y install rsyslog rsyslog-mysql unzip zip binutils cpp fetchmail flex gcc libarchive-zip-perl libc6-dev libcompress-zlib-perl libpcre3 libpopt-dev lynx m4 make ncftp nmap openssl perl perl-modules zlib1g-dev autoconf automake1.9 libtool bison autotools-dev g++ mysql-server mysql-client libmysqlclient15-dev apache2 apache2-doc apache2-mpm-prefork apache2-utils libexpat1 ssl-cert libdb4.6-dev libapache2-mod-php5 php5 php5-common php5-curl php5-dev php5-gd php5-idn php-pear php5-imagick php5-imap php5-json php5-mcrypt php5-memcache php5-mhash php5-ming php5-mysql php5-ps php5-pspell php5-recode php5-snmp php5-sqlite php5-tidy php5-xmlrpc php5-xsl
     apt-get -qq -y install linux-kernel-headers
     /etc/init.d/rsyslog restart
     /etc/init.d/mysql restart
     /etc/init.d/apache2 restart
     netstat -tapn
     # mysqladmin -u root -p create rsyslog
     # mysql -u root -p root     
  SHELL


#  config.vm.provision "ansible" do |ansible|
#        ansible.sudo = true
#  	ansible.playbook = "playbook.yml"
#  end

end
